### ISSUE TITLE
Content Security Policy not being applied?

### ISSUE THREAD

**Issue by narskidan** [johnhyde/turf#12]
When I run the app, I see this:

![Screenshot 2023-10-09 at 0 17 19](https://github.com/johnhyde/turf/assets/104947308/17cc161f-cd4f-407e-aa3e-00d9fa9d72e3)

And the browser provides a very good error message in the console:

>Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "default-src 'unsafe-inline' 'unsafe-eval' *". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback. Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'data:' must be added explicitly.

Yet, the app is defining its own CSP via `meta` tag, here:

https://github.com/johnhyde/turf/blob/e1bef2781774ae99a415e856e3991ec1ed1ac561/index.html#L8-L13

Why is this CSP not being applied?

As a short term fix, we could just change these icons to not use data blobs.

**Comment by narskidan** [comment]
PS really excited to see stuff like this getting created on Urbit

**Comment by johnhyde** [comment]
The CSP I included is sometimes overwritten if the hosting provider applies
their own CSP header. Tlon is known to do this, so if you're using Tlon
hosting that's why. I'd recommend complaining to them about it and/or using
a CSP-blocker browser extension to use Turf.

I wish I could easily work around this limitation on my end, but it would
require significant rewrites that in my opinion shouldn't be necessary.

Thanks for your interest, I hope this helps.


пн, 9 окт. 2023 г., 01:09 Darigo ***@***.***>:

**Comment by johnhyde** [comment]
To address your suggestion, data blobs are used in many places in the app,
as well as by the Phaser game engine itself, so I'd have to maintain a fork
to get around this.

пн, 9 окт. 2023 г., 07:34 John Hyde ***@***.***>:

**Comment by narskidan** [comment]
спасибо, товарищ

I've added a browser extension to just disable CSPs on the Chrome I play Turf with. I've also asked the Tlonmen to consider updating their CSP (regretfully, this issue is tracked only in their private issue tracker, and their DevOps-y code is also not public, so I can't just submit a PR).

**Comment by Xenador77** [comment]
Might want to consider adding a link to this issue in the in-app documentation, and/or marking the issue as open with a link to contact Tlon hosting
