### ISSUE TITLE
Perf improvement: refactor `filterGoals` to not use expensive cloneDeep

### ISSUE THREAD

**Issue by datryn-ribdun** [johnhyde/turf#13]
https://github.com/johnhyde/turf/blob/e1bef2781774ae99a415e856e3991ec1ed1ac561/src/lib/pool.js#L269

`filterGoals` is widely used across turf, notably in `sendWave` which gets called whenever the character moves.

I'm not sure if the cloneDeep can just be entirely removed from `filterGoals` - it would depend on if anything in `filterGoals` could mutate the `rock` argument. From what I could tell, nothing does (`fGoals`, `wash`, `filterGoal`), but someone more familiar with the codebase should weigh in.

`cloneDeep` is pretty expensive and running turf in a profiler suggests that not having to call it would save significant compute.

TODO: attach a flame graph of the profiler where I see `cloneDeep` taking up a ton of the calls that turf makes.

**Comment by datryn-ribdun** [comment]
Unrelated to this perf issue, but `isTextInputFocused` gets called ALOT more than is probably necessary.

**Comment by johnhyde** [comment]
Oof, I wish I'd got around to this sooner. It turned out to be a pretty simple fix. filterGoals _does_ mutate a rock (otherwise it would be applying successive goals to out-of-date state), but it turns out instead of cloning to protect the original rock I can just let filterGoals mutate the current "optimistic" rock and make sure that addCharge and addPulse don't mutate it further for the same resultant grits. Moving around is much faster now (in the latest commit on dev, not yet in the live app)!
